[workspace]
members = ["./pandora/"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
futures-core = { version = "0.3.26" }
kanal = { version = "0.1.0-pre8" }
tokio = { version = "1.25.0" }
